CREATE TABLE `user` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`nameus` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'cp1250_general_ci',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='cp1250_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE `liked` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`likes` BIGINT(19) NOT NULL DEFAULT '0',
	`nameus` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'cp1250_general_ci',
	`userId` INT(10) NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `userId` (`userId`) USING BTREE,
	CONSTRAINT `userlikeFK` FOREIGN KEY (`userId`) REFERENCES `systemlike`.`user` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='cp1250_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE `dislike` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`dis` BIGINT(19) NOT NULL DEFAULT '0',
	`nameus` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'cp1250_general_ci',
	`userId` INT(10) NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `userId` (`userId`) USING BTREE,
	CONSTRAINT `userdisFK` FOREIGN KEY (`userId`) REFERENCES `systemlike`.`user` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='cp1250_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;